name: build_release.yml
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always
jobs:
  build_in_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: "😄 Checkout env"
        run: |
          rustup default nightly
          rustup component add rust-src --toolchain nightly-x86_64-pc-windows-msvc
          rustup update
          cargo +nightly build -Z trim-paths -Z build-std --release
      - name: Prepare artifacts
        run: |
          mkdir -p ./output
          copy ./target/release/rnacos.exe ./output/rnacos.exe
      - name: Pack artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rnacos_windows
          compression-level: 9
          path: output

  build_in_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "😄 Checkout env"
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain nightly --profile default -y
          rustup default nightly
          rustup component add rust-src
          rustup target add x86_64-unknown-linux-musl aarch64-unknown-linux-musl
          cargo install cargo-zigbuild
          sudo snap install zig --classic --beta
          export RUSTFLAGS="-C default-linker-libraries \
            -Z external-clangrt \
            -Z macro-backtrace \
            -Z remap-cwd-prefix=. \
            -Z dep-info-omit-d-target \
            -C llvm-args=-enable-ml-inliner=release \
            -C llvm-args=-inliner-interactive-include-default \
            -C llvm-args=-ml-inliner-model-selector=arm64-mixed \
            -C llvm-args=-ml-inliner-skip-policy=if-caller-not-cold \
            -C link-args=-fomit-frame-pointer \
            -C link-args=-static-libgcc \
            -C link-args=-static-libstdc++ \
            -C llvm-args=-mergefunc-use-aliases \
            -C llvm-args=-enable-shrink-wrap=1 \
            -C llvm-args=-enable-gvn-hoist \
            -C llvm-args=-enable-loop-versioning-licm \
            -C link-args=-Wl,-O3,--gc-sections,--as-needed \
            -C link-args=-Wl,-z,norelro,-x,-s,--strip-all,-z,now
          " 
          export CFLAGS="-Wno-error=date-time"
          cargo-zigbuild +nightly zigbuild --target=x86_64-unknown-linux-musl -Z trim-paths -Z build-std --release
          cargo-zigbuild +nightly zigbuild --target=aarch64-unknown-linux-musl -Z trim-paths -Z build-std --release
      - name: Prepare artifacts
        run: |
          mkdir -p ./output
          cp ./target/x86_64-unknown-linux-musl/release/rnacos ./output/rnacos_x86_64-unknown-linux-musl
          cp ./target/aarch64-unknown-linux-musl/release/rnacos ./output/rnacos_aarch64-unknown-linux-musl
      - name: Pack artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rnacos_linux
          compression-level: 9
          path: output
