name: Book Publish

#v

on:
  push:
    branches:
      - master 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            changed:
              - 'book/**'
              - '.github/workflows/mdbook.yml'
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        if: ${{ steps.changes.outputs.changed == 'true' || startsWith(github.ref, 'refs/tags/') }}
        with:
          mdbook-version: '0.4.10'
          # mdbook-version: 'latest'
      - name: mdbook build
        if: ${{ steps.changes.outputs.changed == 'true' || startsWith(github.ref, 'refs/tags/') }}
        run: | 
          cd book
          mdbook build
          cd -
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ steps.changes.outputs.changed == 'true' || startsWith(github.ref, 'refs/tags/') }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/book

